AWSTemplateFormatVersion: "2010-09-09"
Description: IAM user for GitHub Actions with strict permissions for CodeServer stack

Resources:
  GitHubActionsUser:
    Type: AWS::IAM::User
    Properties:
      UserName: gh-actions
      Tags:
        - Key: Purpose
          Value: GitHubActions-CodeServer

  GitHubActionsPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: GitHubActionsCodeServerStrict
      Users:
        - !Ref GitHubActionsUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # CloudFormation (stack names dinámicos, no se puede restringir el ARN)
          - Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:UpdateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
              - cloudformation:GetTemplateSummary
            Resource: "*"

          # EC2 y Security Groups (no se puede restringir el recurso por ARN)
          - Effect: Allow
            Action:
              - ec2:RunInstances
              - ec2:TerminateInstances
              - ec2:DescribeInstances
              - ec2:DescribeImages
              - ec2:CreateSecurityGroup
              - ec2:AuthorizeSecurityGroupIngress
              - ec2:AuthorizeSecurityGroupEgress
              - ec2:RevokeSecurityGroupIngress
              - ec2:RevokeSecurityGroupEgress
              - ec2:DeleteSecurityGroup
              - ec2:DescribeSecurityGroups
              - ec2:DescribeSubnets
              - ec2:DescribeVpcs
            Resource: "*"

          # IAM - Solo para el rol VSCodeServerIAMRole
          - Effect: Allow
            Action:
              - iam:CreateRole
              - iam:GetRole
              - iam:DeleteRole
            Resource: "arn:aws:iam::*:role/VSCodeServerIAMRole"

          # IAM - Solo para la política AmazonEC2RoleforSSM
          - Effect: Allow
            Action:
              - iam:AttachRolePolicy
              - iam:DetachRolePolicy
            Resource: "arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM"

          # IAM - Solo para el InstanceProfile que usa la instancia
          - Effect: Allow
            Action:
              - iam:CreateInstanceProfile
              - iam:AddRoleToInstanceProfile
              - iam:RemoveRoleFromInstanceProfile
              - iam:DeleteInstanceProfile
              - iam:GetInstanceProfile
            Resource: "arn:aws:iam::*:instance-profile/InstanceProfile"

          # IAM - Permitir solo listar roles y políticas (necesario para CloudFormation)
          - Effect: Allow
            Action:
              - iam:ListRoles
              - iam:ListInstanceProfiles
              - iam:ListPolicies
              - iam:GetPolicy
            Resource: "*"

          # CloudFront - acceso mínimo requerido
          - Effect: Allow
            Action:
              - cloudfront:CreateDistribution
              - cloudfront:UpdateDistribution
              - cloudfront:GetDistribution
              - cloudfront:DeleteDistribution
              - cloudfront:CreateCachePolicy
              - cloudfront:UpdateCachePolicy
              - cloudfront:DeleteCachePolicy
            Resource: "*"

  # Política de solo lectura para recursos IAM (opcional, pero útil para troubleshooting)
  GitHubActionsReadOnlyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: GitHubActionsReadOnly
      Users:
        - !Ref GitHubActionsUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - iam:GetUser
              - iam:GetRole
              - iam:GetInstanceProfile
              - iam:GetPolicy
              - iam:ListRoles
              - iam:ListInstanceProfiles
              - iam:ListPolicies
            Resource: "*"

  GitHubActionsAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref GitHubActionsUser

Outputs:
  GitHubActionsUserName:
    Description: Nombre del usuario IAM creado para GitHub Actions
    Value: !Ref GitHubActionsUser
    Export:
      Name: GitHubActionsUserName
